FROM alpine
MAINTAINER CAtholabs <catholabs@catho.com>
WORKDIR /tmp/

# System packages
RUN apk update && apk add \
    gcc \
    g++ \
    python \
    py-pip \
    libjpeg \
    freetype \
    py-pillow \
    python-dev \
    bash \
    libxft-dev \
    pkgconf\
    pkgconfig \
    python-dev \
    curl \
    make 

# REQUIREMENTS
RUN pip install requests
RUN BLAS=~/src/BLAS/libfblas.a LAPACK=~/src/lapack-3.5.0/liblapack.a pip install numpy==1.9.2
RUN BLAS=~/src/BLAS/libfblas.a LAPACK=~/src/lapack-3.5.0/liblapack.a pip install matplotlib==1.4.3
